// AUTO-GENERATED by scripts/prepare-models.mjs — do not edit.
export const AVAILABLE_MODELS: readonly string[] = [
  "bomb",
  "cricket",
  "product"
];

export function hasModel(name: string): boolean {
  return AVAILABLE_MODELS.includes(name);
}
