/**
 * Compresses every GLB in "3d models/" into public/models/ and regenerates
 * src/three/models.generated.ts so scenes know which models exist.
 *
 * Drop a new model in "3d models/" with one of the expected names, then:
 *   npm run models
 */
import { execSync } from "node:child_process";
import { existsSync, readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const srcDir = join(root, "3d models");
const outDir = join(root, "public", "models");
mkdirSync(outDir, { recursive: true });

/** source filename (lowercase) → { out, mode } */
const MAP = {
  "rainbow_morph_animation.glb": { out: "product", mode: "draco" }, // animated — geometry-only compression
  "ball cricket_glb.glb": { out: "cricket", mode: "optimize" },
  "atomic_bomb.glb": { out: "bomb", mode: "optimize" },
  "system.glb": { out: "system", mode: "optimize" },
  "enclave.glb": { out: "enclave", mode: "optimize" },
  "receipt.glb": { out: "receipt", mode: "optimize" },
  "ledger.glb": { out: "ledger", mode: "optimize" },
  "merkle.glb": { out: "merkle", mode: "optimize" },
  "vision.glb": { out: "vision", mode: "optimize" },
};

const available = [];
for (const file of readdirSync(srcDir)) {
  const entry = MAP[file.toLowerCase()];
  if (!entry) {
    if (file.toLowerCase().endsWith(".glb")) {
      console.warn(`! skipping unrecognized model "${file}" — see 3d models/README.md for expected names`);
    }
    continue;
  }
  const src = join(srcDir, file);
  const out = join(outDir, `${entry.out}.glb`);
  const cmd =
    entry.mode === "draco"
      ? `npx gltf-transform draco "${src}" "${out}"`
      : `npx gltf-transform optimize "${src}" "${out}" --compress draco --texture-compress webp --texture-size 1024`;
  console.log(`> ${file} → public/models/${entry.out}.glb (${entry.mode})`);
  execSync(cmd, { stdio: "inherit", cwd: root });
  available.push(entry.out);
}

// vision falls back to the product object when no dedicated model is supplied
if (!available.includes("vision") && available.includes("product")) {
  available.push("vision:product");
}

const ts = `// AUTO-GENERATED by scripts/prepare-models.mjs — do not edit.
export const AVAILABLE_MODELS: readonly string[] = ${JSON.stringify(
  available.filter((a) => !a.includes(":")),
  null,
  2,
)};

export function hasModel(name: string): boolean {
  return AVAILABLE_MODELS.includes(name);
}
`;
writeFileSync(join(root, "src", "three", "models.generated.ts"), ts);
console.log(`\nAvailable models: ${available.join(", ")}`);
if (!existsSync(join(outDir, "receipt.glb"))) {
  console.log("Missing concept models (system/enclave/receipt/ledger/merkle) — their scenes stay dormant until supplied.");
}
